# Generated by Django 5.1.5 on 2025-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
